---
  spring:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/study0918
      username: root
      password: dnflwlq1
    jpa:
      show-sql: true
      properties:
        hibernate:
          format-sql: true
          ddl-auto: update

---