server:
  servlet:
    context-path: /api
  port: 8081
  session:
    timeout: 1800


spring:
  config:
    import:
      - optional:config/database.yml

springdoc:
  version: 1.0.0
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs
  show-actuator: true
  